### ISSUE TITLE
Help Needed: server side paging ag-grid with angular 2 along with redux + rxjs

### ISSUE THREAD

**Issue by erashu212** [helix46/ag-grid-angular2-beta-ts#3]
Hi @helix46 ,

I have built up my application with help of angular 2 + ngredux + rxjs.
I want to use your ag-grid with technology stack but I am not able find out a way to work with this technology stack.

Can you please assist me to get the server side paging done with above technology stack.

You help would really be appreciated.

Thanks

**Comment by helix46** [comment]
sorry can't help
