### ISSUE TITLE
Unable to render the grid

### ISSUE THREAD

**Issue by ashish-y** [helix46/ag-grid-angular2-beta-ts#7]
Hi,
I download the sample and installed the packages using
npm install

After running the application 
I don't see the grid.

Tried few things but in vain.

Any pointers?

Thanks!

**Comment by helix46** [comment]
What version of npm are you using?

How did you run the application?

Did you see any errors in the console?

**Comment by ashish-y** [comment]
What version of npm are you using?
**3.7.3**

How did you run the application?
**npm start**

Did you see any errors in the console?
**No errors in the console.**

**Comment by helix46** [comment]
Did you run 

npm install 

in the root directory… 

is there a folder node_modules with lots of folders in it?

**Comment by ashish-y** [comment]
Did you run

npm install
**Yes!**
in the root directory…

is there a folder node_modules with lots of folders in it?
**Yes!**

**Comment by helix46** [comment]
Have you compiled the typescript?

Open a command window in the root of the code and  type:

 

npm run tsc:w

 

The code is based on the Angular2 quickstart:

https://angular.io/docs/ts/latest/quickstart.html

 

Are you able to get this tutorial to run?

**Comment by ashish-y** [comment]
Have you compiled the typescript?
Open a command window in the root of the code and  type:
npm run tsc:w

**tried this as well**

The code is based on the Angular2 quickstart:

https://angular.io/docs/ts/latest/quickstart.html

Are you able to get this tutorial to run?

**Yes I'm able to get this tutorial working.**

attached screenshot (added the text "Grid Test" myself)
![image](https://cloud.githubusercontent.com/assets/2869039/18304691/7a180028-7501-11e6-93c0-e4894a4d3351.png)

**Comment by helix46** [comment]
Could you show me the html?

**Comment by ashish-y** [comment]
SampleAppComponent.ts

```
import {Component} from '@angular/core';
import {AgGridNg2} from 'ag-grid-ng2/main';
import {GridOptions} from 'ag-grid/main';

@Component({
    selector: 'app',
    template: `<h1>Grid Test</h1>
    <ag-grid-ng2 class="ag-fresh" style="height: 300px" [rowGroupPanelShow]="always" [columnDefs]="columnDefs"  [rowData] = "rowData"></ag-grid-ng2>`,
    directives: [AgGridNg2]
})


export class SampleAppComponent {
    columnDefs = [
        { headerName: "Make", field: "make" },
        { headerName: "Model", field: "model" },
        {
            headerName: "Price",
            field: "price",
            cellClass: 'rightJustify',
            cellRenderer: function (params: any) {
                return '$' + params.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","); //thanks http://stackoverflow.com/users/28324/elias-zamaria
            }
        }
    ];
    // put data directly onto the controller
    rowData = [
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 }
    ];
    GridOptions: GridOptions = {
        columnDefs: this.columnDefs,
        rowData: this.rowData
    }
}
```

index.html

```
<!DOCTYPE html>
<html>

<head>

    <base href="app">

    <!--ag-grid styles-->
    <link href="node_modules/ag-grid/dist/styles/ag-grid.css" rel="stylesheet" />
    <link href="node_modules/ag-grid/dist/styles/theme-fresh.css" rel="stylesheet" />
    <link href="app/grid.css" rel="stylesheet" />

    <!--angular 2-->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="systemjs.config.js"></script>

    <!--ag-grid-->
    <script src="node_modules/ag-grid/dist/ag-grid.js"></script>

    <script>
        System.config({
            packages: {
                lib: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ag-grid-ng2': {
                    defaultExtension: "js"
                },
                'ag-grid': {
                    defaultExtension: "js"
                },
                'ag-grid-enterprise': {
                    defaultExtension: "js"
                }
            },
            map: {
                'ag-grid-ng2': 'node_modules/ag-grid-ng2',
                'ag-grid': 'node_modules/ag-grid'
            }
        });

        SystemJS.config({ packages: { src: { format: 'register', defaultExtension: 'js' } } });
        SystemJS.import('app/main')
          .then(null, console.error.bind(console));
    </script>
</head>

<body>
    <app>Loading...</app>
</body>

</html>

```

**Comment by helix46** [comment]
Ok thanks

I’m able to repeat the error, and I’m working on a solution

**Comment by helix46** [comment]
OK, appears to be fixed, could you test please.

The problem was that there was no width in the style of the grid. Previously it was not necessary.

Change this line:

<ag-grid-ng2 class="ag-fresh" style="height: 300px;" [columnDefs]="columnDefs"  [rowData] = "rowData"></ag-grid-ng2>

to this;

<ag-grid-ng2 class="ag-fresh" style="height: 300px; width: 800px;" [columnDefs]="columnDefs"  [rowData] = "rowData"></ag-grid-ng2>

 

Also, I’ve upgraded to Angular2 rc6

**Comment by ashish-y** [comment]
It's working now.

I thought I tried that width thing but it didn't work for me.

Anyways, Thanks!
